"use client";
import { useEffect, useMemo, useState } from "react";
import { Activity, ArrowUpRight, BarChart3, Bell, BookOpen, ChevronRight, Filter, LayoutDashboard, ListFilter, Search, Settings2, ShieldCheck, Star, TrendingUp, Zap } from "lucide-react";

type Status = "Forming" | "Ready" | "Failed";
type Scan = { monthlyRsi:number; weeklyRsi:number; dailyRsi:number; dailyRsiPrevious:number; entry:number; stopLoss:number; target:number; relativeVolume:number; riskReward:number; ready:boolean; score:number; setupType:string; reasons:string[] };
type Stock = { symbol:string; company:string; sector:string; instrumentKey:string; candleCount:number; ok:boolean; error?:string; scan?:Scan };

const seed: Stock[] = [
 {symbol:"INFY",company:"Infosys",sector:"IT",instrumentKey:"NSE_EQ|INE009A01021",candleCount:0,ok:false},
 {symbol:"RELIANCE",company:"Reliance Industries",sector:"Energy",instrumentKey:"NSE_EQ|INE002A01018",candleCount:0,ok:false},
 {symbol:"TCS",company:"Tata Consultancy Services",sector:"IT",instrumentKey:"NSE_EQ|INE467B01029",candleCount:0,ok:false},
 {symbol:"HDFCBANK",company:"HDFC Bank",sector:"Banking",instrumentKey:"NSE_EQ|INE040A01034",candleCount:0,ok:false},
 {symbol:"SBIN",company:"State Bank of India",sector:"Banking",instrumentKey:"NSE_EQ|INE062A01020",candleCount:0,ok:false},
];
const nav:[[string,any],[string,any],[string,any],[string,any],[string,any],[string,any]] = [["Dashboard",LayoutDashboard],["GFS Scanner",Zap],["Breakouts",TrendingUp],["Watchlist",Star],["Backtest",BarChart3],["Signal History",BookOpen]];
function Badge({children,tone="neutral"}:{children:React.ReactNode;tone?:"green"|"amber"|"red"|"blue"|"neutral"}){return <span className={`badge badge-${tone}`}><span className="badge-dot"/>{children}</span>}
function state(s:Stock):Status{return !s.ok||!s.scan?"Failed":s.scan.ready?"Ready":"Forming"}
function StatusBadge({status}:{status:Status}){return <Badge tone={status==="Ready"?"blue":status==="Failed"?"red":"amber"}>{status}</Badge>}
function RsiBars({s}:{s:Stock}){if(!s.scan)return <div className="muted">No live result</div>;const a:[[string,number],[string,number],[string,number]]=[["Monthly",s.scan.monthlyRsi],["Weekly",s.scan.weeklyRsi],["Daily",s.scan.dailyRsi]];return <div className="rsi-stack">{a.map(([label,v])=><div className="rsi-row" key={label}><span>{label}</span><div className="rsi-track"><div className="rsi-fill" style={{width:`${Math.min(v,100)}%`}}/><i style={{left:`${Math.min(v,100)}%`}}/></div><b>{v.toFixed(1)}</b></div>)}</div>}

export default function Home(){
 const [active,setActive]=useState("Dashboard"),[stocks,setStocks]=useState(seed),[loading,setLoading]=useState(true),[error,setError]=useState(""),[query,setQuery]=useState(""),[filterStatus,setFilterStatus]=useState("All"),[sector,setSector]=useState("All sectors"),[selected,setSelected]=useState<Stock|null>(null),[watch,setWatch]=useState(["INFY"]);
 const refresh=async()=>{setLoading(true);setError("");try{const r=await fetch("/api/scanner/gfs/batch",{cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d.error||"Scanner request failed");setStocks(d.results||[])}catch(e){setError(e instanceof Error?e.message:"Unable to load live scanner")}finally{setLoading(false)}};
 useEffect(()=>{refresh()},[]);
 const filtered=useMemo(()=>stocks.filter(s=>(s.symbol.toLowerCase().includes(query.toLowerCase())||s.company.toLowerCase().includes(query.toLowerCase()))&&(filterStatus==="All"||state(s)===filterStatus)&&(sector==="All sectors"||s.sector===sector)),[stocks,query,filterStatus,sector]);
 const valid=stocks.filter(s=>s.ok&&s.scan),ready=valid.filter(s=>state(s)==="Ready").length,forming=valid.filter(s=>state(s)==="Forming").length,avg=valid.length?valid.reduce((n,s)=>n+(s.scan?.score||0),0)/valid.length:0;
 const top=valid.slice().sort((a,b)=>(b.scan?.score||0)-(a.scan?.score||0));
 return <main className="app-shell"><aside className="sidebar"><div className="brand"><div className="brand-mark">M</div><div><strong>Malkan</strong><span>Strategy Lab</span></div></div><div className="live-pill"><span/>{loading?"Scanning live market":"Market engine online"}</div><nav>{nav.map(([label,Icon])=><button key={label} className={active===label?"nav-item active":"nav-item"} onClick={()=>setActive(label)}><Icon size={18}/><span>{label}</span>{label==="GFS Scanner"&&<em>{valid.length}</em>}</button>)}</nav><div className="sidebar-bottom"><button className="nav-item"><Settings2 size={18}/><span>Settings</span></button><div className="data-status"><ShieldCheck size={16}/><div><b>Research mode</b><span>Signals are rule-based<br/>and not recommendations.</span></div></div></div></aside>
 <section className="main-area"><header className="topbar"><div><span className="eyebrow">Live · 01 September 2026</span><h1>{active==="Dashboard"?"Market intelligence":active}</h1></div><div className="top-actions"><button className="icon-btn" onClick={refresh}><Bell size={18}/><i/></button><button className="profile">AR</button></div></header><div className="content">
 {active==="Dashboard"&&<><section className="hero-row"><div className="hero-copy"><Badge tone="green">{loading?"Scanner running":"Live scanner ready"}</Badge><h2>Find the strongest<br/><span>setups before the move.</span></h2><p>Real Upstox market data is passed through the GFS rule engine. These cards are live calculations, not seeded demo signals.</p>{error&&<p className="muted">{error}</p>}</div><div className="market-card"><div className="card-head"><span>GFS UNIVERSE</span><Badge tone={loading?"amber":"green"}>{valid.length}/5 live</Badge></div><div className="market-price">{ready}<strong> ready setups</strong></div><div className="market-meta"><span>Forming <b>{forming}</b></span><span>Scanned <b>{stocks.length}</b></span><span>Mode <b>Live</b></span></div></div></section><section className="metrics-grid"><div className="metric"><span>Ready setups</span><strong>{ready}</strong><small><ArrowUpRight size={13}/> high-conviction queue</small></div><div className="metric"><span>Forming</span><strong>{forming}</strong><small>watch for confirmation</small></div><div className="metric"><span>Successful scans</span><strong>{valid.length}<small>/{stocks.length}</small></strong><small>real Upstox responses</small></div><div className="metric"><span>Average score</span><strong>{avg.toFixed(1)}<small>/10</small></strong><small>across live results</small></div></section><section className="section-head"><div><span className="eyebrow">Live signal queue</span><h3>Top Malkan setups</h3></div><button className="text-btn" onClick={()=>setActive("GFS Scanner")}>Open full scanner <ChevronRight size={15}/></button></section><div className="setup-grid">{top.slice(0,4).map((s,i)=><article className="setup-card" key={s.symbol} onClick={()=>setSelected(s)}><div className="setup-top"><div className="ticker"><div>{s.symbol.slice(0,2)}</div><span><b>{s.symbol}</b><small>{s.company}</small></span></div><button className={watch.includes(s.symbol)?"star active":"star"} onClick={e=>{e.stopPropagation();setWatch(w=>w.includes(s.symbol)?w.filter(x=>x!==s.symbol):[...w,s.symbol])}}><Star size={16} fill="currentColor"/></button></div><div className="setup-name"><span>{String(i+1).padStart(2,"0")}</span>{s.scan?.setupType||"GFS"}</div><div className="score-line"><div><span>Live score</span><b>{(s.scan?.score||0).toFixed(1)}</b></div><div className="score-track"><div style={{width:`${Math.min((s.scan?.score||0)*10,100)}%`}}/></div></div><RsiBars s={s}/><div className="setup-foot"><StatusBadge status={state(s)}/><span>R:R <b>1:{(s.scan?.riskReward||0).toFixed(2)}</b></span></div></article>)}</div></>}
 {active!=="Dashboard"&&<><section className="scanner-intro"><div><Badge tone="blue">Live rule engine</Badge><h2>{active}</h2><p>{active==="GFS Scanner"?"Five-stock live test: Monthly → Weekly → Daily RSI, confirmation, volume, entry, stop-loss, target and risk/reward are calculated from Upstox candles.":"This workflow is prepared for the next scanner expansion."}</p></div><div className="rule-box"><span>Framework</span><b>RSI 60 / 40</b><small>{loading?"Scanning…":"Live calculations"}</small></div></section><section className="toolbar"><div className="search"><Search size={17}/><input placeholder="Search stock or company" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="select"><ListFilter size={16}/><select value={filterStatus} onChange={e=>setFilterStatus(e.target.value)}><option>All</option><option>Ready</option><option>Forming</option><option>Failed</option></select></div><div className="select"><Filter size={16}/><select value={sector} onChange={e=>setSector(e.target.value)}><option>All sectors</option>{Array.from(new Set(stocks.map(s=>s.sector))).map(x=><option key={x}>{x}</option>)}</select></div><button className="text-btn" onClick={refresh} style={{marginLeft:"auto"}}><Activity size={15}/> Refresh live</button></section><div className="table-wrap"><table><thead><tr><th>Stock</th><th>Setup</th><th>Monthly</th><th>Weekly</th><th>Daily</th><th>Volume</th><th>Entry</th><th>SL</th><th>Target</th><th>R:R</th><th>Score</th><th>Status</th></tr></thead><tbody>{filtered.map(s=>{const x=s.scan;return <tr key={s.symbol} onClick={()=>setSelected(s)}><td><div className="table-stock"><span>{s.symbol.slice(0,2)}</span><div><b>{s.symbol}</b><small>{s.company}</small></div></div></td><td className="setup-type">{x?.setupType||s.error||"No result"}</td><td className={x&&x.monthlyRsi>60?"rsi-value green":"rsi-value"}>{x?x.monthlyRsi.toFixed(1):"—"}</td><td className={x&&x.weeklyRsi>60?"rsi-value green":"rsi-value"}>{x?x.weeklyRsi.toFixed(1):"—"}</td><td>{x?x.dailyRsi.toFixed(1):"—"}</td><td>{x?`${x.relativeVolume.toFixed(2)}x`:"—"}</td><td>{x?x.entry.toFixed(2):"—"}</td><td>{x?x.stopLoss.toFixed(2):"—"}</td><td>{x?x.target.toFixed(2):"—"}</td><td>{x?`1:${x.riskReward.toFixed(2)}`:"—"}</td><td className="score-number">{x?x.score.toFixed(1):"—"}</td><td><StatusBadge status={state(s)}/></td></tr>})}</tbody></table></div><div className="disclaimer"><ShieldCheck size={14}/><span><b>Research mode:</b> rule-based calculations for analysis, not investment recommendations.</span></div></>}
 </div></section>{selected&&<div className="modal-backdrop" onClick={()=>setSelected(null)}><div className="detail-modal" onClick={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setSelected(null)}>×</button><div className="detail-title"><div className="big-ticker">{selected.symbol.slice(0,2)}</div><div><span className="eyebrow">{selected.sector} · {selected.company}</span><h2>{selected.symbol}</h2><StatusBadge status={state(selected)}/></div><div className="detail-score"><span>Score</span><b>{selected.scan?.score?.toFixed(1)||"—"}</b><small>/10</small></div></div>{selected.scan&&<><div className="detail-grid" style={{marginTop:20}}><div className="detail-panel"><span className="panel-title">GFS evidence</span><RsiBars s={selected}/><div className="evidence-list">{selected.scan.reasons.length?selected.scan.reasons.map(r=><p key={r}>✓ {r}</p>):<p>No confirmation reasons triggered.</p>}</div></div><div className="detail-panel"><span className="panel-title">Trade levels</span><div className="plan-grid"><div><span>Entry</span><b>₹{selected.scan.entry.toFixed(2)}</b></div><div><span>Stop loss</span><b>₹{selected.scan.stopLoss.toFixed(2)}</b></div><div><span>Target</span><b>₹{selected.scan.target.toFixed(2)}</b></div><div><span>Risk / reward</span><b>1:{selected.scan.riskReward.toFixed(2)}</b></div></div></div></div><div className="why"><b>Current rule result</b><p>{selected.scan.ready?"All required GFS conditions currently pass.":"The current rules do not confirm a ready GFS setup."}</p></div></>}</div></div>}
 </main>;
}
